### PR TITLE
Add results refresh

### PR DESCRIPTION
**Pull request by acang-gs**
Major feature additions:
- Users can now see when performance results are not up to date (i.e. is_dirty = true), and the latest update time on the data entry form
- When results are out of date, a refresh link is rendered, which triggers a recalculation when clicked
- When recalculation is complete, the performance summary data are refreshed for the user to view

Minor revisions:
- Fixed tooltip bug that caused map view state to oscillate when tooltip rendered too close to edge of map
- Fixed point scaling bug that caused BMP's to be rendered too large at high zoom levels
- Improved result table column widths

### CODE REVIEW

**Comment by acang-gs** [comment]
@austinorr Sorry to bother you - but it looks like I'm having some log in issues with GCR. Any chance you can help debug so we can deploy new features to dev?

**Comment by austinorr** [comment]
@acang-gs Hm, i looked at the secrets information for our repo and found this: 
image

"secrets aren't passed to any workflows triggered by PRs from a fork"

looks like we can only resolve by not using forks for PRs and instead opening the PR from a new branch on this repo.

**Comment by acang-gs** [comment]
@austinorr interesting - I've created successfully passing PR's in the past from my fork, or so I thought. There appears to have been some [features](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) developed back in 2020 that should help with this issue:

_ Improvements for public repository forks

GitHub Actions has always been about more than just continuous integration. Our goal is to enable repository maintainers to automate a variety of workflows and reduce manual effort. In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets. This makes common workflows like labeling or commenting on pull requests very difficult.

In order to solve this, we’ve added a new pull_request_target event, which behaves in an almost identical way to the pull_request event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request. This event can be used in combination with the private repository settings as well._

That being said, I can try to create a PR from the main repo as well.

**Comment by austinorr** [comment]
go ahead and open the PR from your upstream. i'll look into the pull_request_target event and let you know what i find out.

**Comment by acang-gs** [comment]
@austinorr I'm going to open a PR directly from this repo - closing this one down

**Comment by austinorr** [comment]
@acang-gs I looked into this and i think we should keep things as-is with no builds from forks. Using our GCR as a build cache for our PR's is a big speed boost, but on a public repo it's not safe to run code from just any fork. Your old builds used to work before I added caching to the CI, but i think the trade off is worth it since it's just as easy to push to upstream as it is to push to origin.

I do apologize for not giving you a heads up, i actually didn't know that the actions secrets weren't shared with PR's from forks.

**Pull request closed without merging**
